import TypeFragment from '../../interfaces/type-fragment';

export const commonCodes: TypeFragment[] = [
    "amazonaws",
    "m2d",
    "atom",
    "sdk",
    "rss",
    "ajax",
    "shadowbox",
    "modernizr",
    "swfobject",
    "jquery",
    "mrp",
    "mozilla",
    "chrome",
    "flashplayer",
    "videolan",
    "trackjs",
    "cdnjs",
    "trackjs",
    "xmlrpc",
    "polyfill",
    "manifest",
    "gstatic",
    "wordpress",
    "navdmp",
    "spreaker",
    "googleapis",
    "html5shim",
    "googlecode",
    "smartlook",
    "onelink",
    "slitslider",
    "addthis",
    "itunes",
    "fontawesome",
];

export default commonCodes;
