import TypeFragment from '../../interfaces/type-fragment';

export const commonCodes: TypeFragment[] = [
    "amazonaws",
    "m2d",
    "atom",
    "sdk",
    "rss",
    "rss",
    "ajax",
    "shadowbox",
    "modernizr",
    "swfobject",
    "jquery",
    "mrp",
    "mozilla",
    "chrome",
    "flashplayer",
    "videolan",

    // ################## tests #################
    "trackjs",
    "vlc",
    "cdnjs",
    "m2d",
    "trackjs",
    // "xmlrpc",
    "polyfill",
    "manifest",
    "gstatic",
    // "developer",
    "wordpress",
    // "gmpg",
    "navdmp",
    // "spreaker",
    // "googleapis",
    "html5shim",
    "googlecode",
    "smartlook",
    // "onelink",
    "slitslider",
    // "addthis",
    "itunes",
    // "fontawesome",
];

export default commonCodes;
