import TypeFragment from '../../interfaces/type-fragment';

export const commonDomains: TypeFragment[] = [
    "google",
    "youtube",
    "macromedia",
    "facebook",
    "onelink",
    "store",
    "apple",
    "cloudflare",
    "creativebizz",
    "softonic.com",
    "purl.org",
    "w3.org",
    "audients.com",
    "squareup.com",
    "netflix.com",
    "spotify.com",
    "vk.com",
    "pinterest.com",
    "soundcloud.com",
    "amazon.com",
    "mailchimp.com",
    "adobe.com",
    "gs1.org",
    "github.com",
    "wikipedia.org",
    "schema.org",
    "ebay.com",
    "tag.navdmp.com",
    // "cdn.webrad.io",
    // "gs1.org",
    "w.org",
    // "viralcure.org",
    // "gstatic.com",
    "twitch.tv",
    // "bbc.co",
    "t.co",
    // "nugs.tv",
    // "vvhp.net",
    // "gc2labs.com.br",
    // "hackrads.com.br",
];

export default commonDomains;
